name: flame_demo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flame: ^1.8.0

  flame_rive: ^1.8.0

  flame_lottie: ^0.2.0+3

  flame_tiled: ^1.10.2

  flame_spine: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/anims/
    - assets/spine/
    - assets/tiles/
    - assets/images/
    - assets/images/tiles/
    - assets/images/bg/bigMap/
    - assets/images/bg/map/
    - assets/images/icons/
    - assets/images/models/singleSkill/
    - assets/images/models/mulSkill/crtz/
    - assets/images/models/mulSkill/effect_test/
    - assets/images/models/mulSkill/feidao/
    - assets/images/models/mulSkill/fsyj/
    - assets/images/models/mulSkill/tqzyj/
    - assets/images/models/mulSkill/yujianshu/
#    - assets/images/models/singleModel/fe_bian01/
#    - assets/images/models/singleModel/fe_dao01/
#    - assets/images/models/singleModel/fe_fashi01/
#    - assets/images/models/singleModel/fe_fashi02/
#    - assets/images/models/singleModel/fe_jian02/
#    - assets/images/models/singleModel/fe_jian03/
#    - assets/images/models/singleModel/fe_jian05/
#    - assets/images/models/singleModel/fe_kongshou01/
#    - assets/images/models/singleModel/fe_kongshou02/
#    - assets/images/models/singleModel/fe_kongshou03/
#    - assets/images/models/singleModel/fe_kongshou04/
#    - assets/images/models/singleModel/fe_kongshou05/
#    - assets/images/models/singleModel/fe_kongshou06/
#    - assets/images/models/singleModel/fe_kongshou08/
#    - assets/images/models/singleModel/fe_qin02/
#    - assets/images/models/singleModel/fe_shanzi01/
#    - assets/images/models/singleModel/fe_shanzi02/
#    - assets/images/models/singleModel/fe_wandao01/
#    - assets/images/models/singleModel/jian01/
    - assets/images/models/singleModel/jian02/
#    - assets/images/models/singleModel/jian03/
#    - assets/images/models/singleModel/jian04/
#    - assets/images/models/singleModel/jian05/
#    - assets/images/models/singleModel/jian08/
    - assets/images/models/singleModel/jian10/
#    - assets/images/models/singleModel/jujian01/
#    - assets/images/models/singleModel/jujian02/
#    - assets/images/models/singleModel/jujian03/
#    - assets/images/models/singleModel/kongshou01/
    - assets/images/models/singleModel/kongshou04/
#    - assets/images/models/singleModel/kongshou05/
    - assets/images/models/singleModel/kongshou06/
#    - assets/images/models/singleModel/kongshou07/
#    - assets/images/models/singleModel/shanzi01/
    - assets/images/models/singleModel/shanzi03/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
